- name: Deploy Docker container
  hosts: webservers
  become: yes

  tasks:
    - name: Docker image on target servers
      docker_image:
        name: myapp
        tag: v1
        source: local

    - name: Run Docker container
      docker_container:
        name: myapp-container
        image: myapp:v1
        state: started
        ports:
          - "8090:8090"
