- name: Deploy Docker container
  hosts: webserver
  become: yes

  vars:
    image_name: "devenops641/myapp:{{ image_tag }}"

  tasks:

    - name: Install Docker and dependencies
      apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove old container if exists
      docker_container:
        name: myapp-container
        state: absent

    - name: Run new Docker container
      docker_container:
        name: myapp-container
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        pull: yes
        ports:
          - "8090:8090"

